import {
    Command,
    ArrowLeft,
    ArrowRight,
    Link,
    Sparkles,
    Star,
    AlertCircle,
    Candy,
    ChevronUp,
    ChevronDown,
    BellRing,
    Search,
    X,
    Shell,
    BookA,
} from 'lucide-react'

export const Icons = {
    logo: Command,
    arrowLeft: ArrowLeft,
    arrowRight: ArrowRight,
    link: Link,
    sparkles: Sparkles,
    star: Star,
    alert: AlertCircle,
    candy: Candy,
    chevronUp: ChevronUp,
    chevronDown: ChevronDown,
    bellRing: BellRing,
    search: Search,
    cross: X,
    shell: Shell,
    book: BookA,
}